"""
Ollama Prometheus Metrics Exporter
-----------------------------------
A lightweight sidecar that polls Ollama API and exposes Prometheus metrics.
Built for the DrDroid DevRel assignment - demonstrates instrumenting LLM
observability when the underlying tool does not expose metrics natively.
"""

import os
import time
import json
import logging
from http.server import HTTPServer, BaseHTTPRequestHandler
from threading import Thread
from urllib import request as urlrequest
from urllib.error import URLError

from prometheus_client import (
    CollectorRegistry,
    Gauge,
    Counter,
    Histogram,
    generate_latest,
    CONTENT_TYPE_LATEST,
)

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(message)s",
)
log = logging.getLogger("ollama-exporter")

OLLAMA_URL = os.environ.get("OLLAMA_URL", "http://localhost:11434")
METRICS_PORT = int(os.environ.get("METRICS_PORT", "9101"))
POLL_INTERVAL = int(os.environ.get("POLL_INTERVAL", "10"))
PROBE_MODEL = os.environ.get("PROBE_MODEL", "llama3.2:1b")
PROBE_PROMPT = os.environ.get("PROBE_PROMPT", "Hi")

registry = CollectorRegistry()

ollama_up = Gauge(
    "ollama_up",
    "Is the Ollama API responding (1=yes, 0=no)",
    registry=registry,
)
loaded_models = Gauge(
    "ollama_loaded_models",
    "Number of models currently loaded into memory",
    registry=registry,
)
installed_models = Gauge(
    "ollama_installed_models",
    "Number of models installed on disk",
    registry=registry,
)
model_size_bytes = Gauge(
    "ollama_model_size_bytes",
    "Size of a loaded model in bytes",
    ["model"],
    registry=registry,
)
request_duration = Histogram(
    "ollama_request_duration_seconds",
    "Inference latency for synthetic probe requests",
    ["model"],
    buckets=(0.5, 1, 2, 5, 10, 20, 30, 60, 120),
    registry=registry,
)
tokens_total = Counter(
    "ollama_tokens_total",
    "Total tokens generated by synthetic probe requests",
    ["model"],
    registry=registry,
)
tokens_per_second = Gauge(
    "ollama_tokens_per_second",
    "Tokens per second from last synthetic probe request",
    ["model"],
    registry=registry,
)
probe_errors_total = Counter(
    "ollama_probe_errors_total",
    "Total probe errors by type",
    ["error_type"],
    registry=registry,
)


def http_get_json(path: str, timeout: int = 5):
    req = urlrequest.Request(f"{OLLAMA_URL}{path}", method="GET")
    with urlrequest.urlopen(req, timeout=timeout) as resp:
        return json.loads(resp.read())


def http_post_json(path: str, body: dict, timeout: int = 60):
    data = json.dumps(body).encode("utf-8")
    req = urlrequest.Request(
        f"{OLLAMA_URL}{path}",
        data=data,
        method="POST",
        headers={"Content-Type": "application/json"},
    )
    with urlrequest.urlopen(req, timeout=timeout) as resp:
        return json.loads(resp.read())


def poll_health_and_models():
    try:
        tags = http_get_json("/api/tags")
        installed = tags.get("models", [])
        installed_models.set(len(installed))
        for m in installed:
            name = m.get("name", "unknown")
            size = m.get("size", 0)
            model_size_bytes.labels(model=name).set(size)

        ps = http_get_json("/api/ps")
        running = ps.get("models", [])
        loaded_models.set(len(running))
        ollama_up.set(1)
    except (URLError, TimeoutError, Exception) as e:
        ollama_up.set(0)
        probe_errors_total.labels(error_type="health").inc()
        log.warning("Health poll failed: %s", e)


def run_probe():
    body = {
        "model": PROBE_MODEL,
        "prompt": PROBE_PROMPT,
        "stream": False,
        "options": {"num_predict": 5},
    }
    try:
        with request_duration.labels(model=PROBE_MODEL).time():
            result = http_post_json("/api/generate", body, timeout=60)

        eval_count = result.get("eval_count", 0)
        eval_duration_ns = result.get("eval_duration", 0)

        if eval_count > 0:
            tokens_total.labels(model=PROBE_MODEL).inc(eval_count)

        if eval_count > 0 and eval_duration_ns > 0:
            tps = eval_count / (eval_duration_ns / 1e9)
            tokens_per_second.labels(model=PROBE_MODEL).set(tps)
    except Exception as e:
        probe_errors_total.labels(error_type="probe").inc()
        log.warning("Probe failed: %s", e)


def poller():
    log.info(
        "Starting poller: url=%s interval=%ss probe_model=%s",
        OLLAMA_URL, POLL_INTERVAL, PROBE_MODEL,
    )
    while True:
        poll_health_and_models()
        run_probe()
        time.sleep(POLL_INTERVAL)


class MetricsHandler(BaseHTTPRequestHandler):
    def do_GET(self):
        if self.path == "/metrics":
            output = generate_latest(registry)
            self.send_response(200)
            self.send_header("Content-Type", CONTENT_TYPE_LATEST)
            self.send_header("Content-Length", str(len(output)))
            self.end_headers()
            self.wfile.write(output)
        elif self.path in ("/", "/healthz"):
            self.send_response(200)
            self.send_header("Content-Type", "text/plain")
            self.end_headers()
            self.wfile.write(b"ollama-exporter ok\n")
        else:
            self.send_response(404)
            self.end_headers()

    def log_message(self, format, *args):
        pass


def main():
    Thread(target=poller, daemon=True).start()
    log.info("Metrics server listening on :%s", METRICS_PORT)
    HTTPServer(("0.0.0.0", METRICS_PORT), MetricsHandler).serve_forever()


if __name__ == "__main__":
    main()
